language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_deploy: "echo 'ready?'"
deploy:
  provider: heroku
  api_key: f34d08d7e0c68bc2227baaeef149261fba6679a2
  app: arcane-falls-36452
after_deploy: "echo 'done'"


